Name:           arm-frc-linux-gnueabi-eglibc
Version:        2.23
Release:        1%{?dist}
Summary:        Kernel headers for use in FRC 2018 Power Up

%define _basever 2.23-r0.47
%define _target arm-frc-linux-gnueabi

License:        GPLv3
URL:            http://www.eglibc.org
Source0:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/libc6-dev_%{_basever}_cortexa9-vfpv3.ipk
Source1:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/libc6_%{_basever}_cortexa9-vfpv3.ipk
Source2:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/libcidn1_%{_basever}_cortexa9-vfpv3.ipk
Source3:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/libc6-thread-db_%{_basever}_cortexa9-vfpv3.ipk 
Source4:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/libc6-extra-nss_%{_basever}_cortexa9-vfpv3.ipk

BuildRequires: arm-frc-linux-gnueabi-binutils

%description
Kernel headers for use in FRC 2018 Power Up. Sanitized for use in userspace %{_target} 

%global _enable_debug_package 0
%global debug_package %{nil}
%global __os_install_post /usr/lib/rpm/brp-compress %{nil}

%define version 2.23
%define builddir eglibc-%{version}
%prep
rm -rf %{builddir}
mkdir -p %{builddir}
cd %{builddir}
for file in %{_sourcedir}/lib*.ipk; do
    ar x $file
    tar xf data.tar.gz
done

%define installdir %{buildroot}/%{_prefix}/%{_target}
%install
cd %{builddir}
mkdir -p %{installdir}
find . \( -name .install -o -name ..install.cmd \) -delete
cp -r lib %{installdir}
for so in %{installdir}/lib/*so; do
    arm-frc-linux-gnueabi-strip $so
    echo $so
done
cp -r usr %{installdir}

%files
%{_prefix}/arm-frc-linux-gnueabi/lib/ld-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/ld-linux.so.3
%{_prefix}/arm-frc-linux-gnueabi/lib/libBrokenLocale-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libBrokenLocale.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libanl-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libanl.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libc-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libc.so.6
%{_prefix}/arm-frc-linux-gnueabi/lib/libcidn-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libcidn.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libcrypt-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libcrypt.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libdl-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libdl.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libm-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libm.so.6
%{_prefix}/arm-frc-linux-gnueabi/lib/libnsl-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnsl.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_compat-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_compat.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_db-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_db.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_dns-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_dns.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_files-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_files.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_hesiod-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_hesiod.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_nis-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_nis.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_nisplus-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libnss_nisplus.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libpthread-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libpthread.so.0
%{_prefix}/arm-frc-linux-gnueabi/lib/libresolv-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libresolv.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/librt-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/librt.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libthread_db-1.0.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libthread_db.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libutil-2.23.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libutil.so.1
%{_prefix}/arm-frc-linux-gnueabi/usr/include/_G_config.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/a.out.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/aio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/aliases.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/alloca.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/argp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/argz.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/ftp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/inet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/nameser.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/nameser_compat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/telnet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/arpa/tftp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/assert.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/a.out.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/byteswap-16.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/byteswap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/cmathcalls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/confname.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/dirent.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/dlfcn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/elfclass.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/endian.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/environments.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/epoll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/error.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/eventfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/fcntl-linux.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/fcntl2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/fenv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/fenvinline.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/huge_val.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/huge_valf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/huge_vall.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/hwcap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/in.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/inf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/initspin.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/inotify.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/ioctl-types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/ioctls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/ipc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/ipctypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/libio-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/libm-simd-decl-stubs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/link.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/local_lim.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/locale.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/math-finite.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/math-vector.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mathcalls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mathdef.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mathinline.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mman-linux.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mman.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/monetary-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mqueue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/mqueue2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/msq.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/nan.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/netdb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/param.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/poll2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/posix1_lim.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/posix2_lim.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/posix_opt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/printf-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/pthreadtypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/resource.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sched.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/select.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/select2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sem.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/semaphore.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/setjmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/setjmp2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/shm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sigaction.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sigcontext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/siginfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/signalfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/signum.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sigset.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sigstack.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sigthread.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sockaddr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/socket2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/socket_type.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stab.def
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/statfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/statvfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdio-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdio2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdio_lim.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdlib-bsearch.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdlib-float.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdlib-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stdlib.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/string.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/string2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/string3.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/stropts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sys_errlist.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/syscall.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/sysctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/syslog-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/syslog-path.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/syslog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/time.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/timerfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/timex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/typesizes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/uio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/ustat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/utmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/utmpx.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/utsname.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/waitflags.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/waitstatus.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/wchar-ldbl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/wchar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/wchar2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/wordsize.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/xopen_lim.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/bits/xtitypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/byteswap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/complex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/cpio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/crypt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ctype.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/dirent.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/dlfcn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/elf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/endian.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/envz.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/err.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/error.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/execinfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/features.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fenv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fmtmsg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fnmatch.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fpu_control.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fstab.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/fts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ftw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gconv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/getopt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/glob.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu-versions.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu/lib-names-soft.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu/lib-names.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu/libc-version.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu/stubs-soft.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gnu/stubs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/grp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/gshadow.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/iconv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ieee754.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ifaddrs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/inttypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/langinfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/lastlog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/libgen.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/libintl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/libio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/limits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/link.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/locale.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/malloc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/math.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mcheck.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/memory.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mntent.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/monetary.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mqueue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/ethernet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if_arp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if_packet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if_ppp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if_shaper.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/if_slip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/ppp-comp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/ppp_defs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/net/route.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netash/ash.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netatalk/at.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netax25/ax25.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netdb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/neteconet/ec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/ether.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/icmp6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/if_ether.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/if_fddi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/if_tr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/igmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/in.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/in_systm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/ip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/ip6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/ip_icmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/tcp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netinet/udp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netipx/ipx.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netiucv/iucv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netpacket/packet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netrom/netrom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/netrose/rose.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/nfs/nfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/nl_types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/nss.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/obstack.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/paths.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/printf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/protocols/routed.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/protocols/rwhod.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/protocols/talkd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/protocols/timed.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/pthread.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/pty.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/pwd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/re_comp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/regex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/regexp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/resolv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/auth.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/auth_des.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/auth_unix.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/clnt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/des_crypt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/key_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/netdb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/pmap_clnt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/pmap_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/pmap_rmt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/rpc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/rpc_des.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/rpc_msg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/svc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/svc_auth.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpc/xdr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/bootparam.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/bootparam_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/bootparam_prot.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/key_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/key_prot.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/klm_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/klm_prot.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/mount.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/mount.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nfs_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nfs_prot.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis_callback.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis_callback.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis_object.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nis_tags.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nislib.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nlm_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/nlm_prot.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rex.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rstat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rstat.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rusers.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/rusers.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/sm_inter.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/sm_inter.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/spray.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/spray.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/yp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/yp.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/yp_prot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/ypclnt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/yppasswd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/yppasswd.x
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rpcsvc/ypupd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sched.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/scsi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/scsi_ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/sg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/search.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/semaphore.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/setjmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sgtty.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/shadow.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/signal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/spawn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stab.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stdc-predef.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stdint.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stdio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stdio_ext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stdlib.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/string.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/strings.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/stropts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/acct.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/auxv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/bitypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/cdefs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/dir.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/elf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/epoll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/eventfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/fanotify.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/file.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/fsuid.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/gmon.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/gmon_out.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/inotify.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/io.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ipc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/kd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/klog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/mman.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/mount.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/msg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/mtio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/param.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/pci.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/personality.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/prctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/procfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/profil.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ptrace.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/queue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/quota.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/raw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/reboot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/resource.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/select.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/sem.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/sendfile.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/shm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/signal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/signalfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/socketvar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/soundcard.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/stat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/statfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/statvfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/stropts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/swap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/syscall.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/sysctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/sysinfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/syslog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/sysmacros.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/time.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/timeb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/timerfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/times.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/timex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ttychars.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ttydefaults.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ucontext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/uio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ultrasound.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/un.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/ustat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/utsname.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/vfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/vlimit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/vt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/vtimes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/wait.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sys/xattr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/syscall.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sysexits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/syslog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/tar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/termio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/tgmath.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/thread_db.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/time.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ttyent.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/uchar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ucontext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ulimit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/ustat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/utime.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/utmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/utmpx.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/values.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/wait.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/wchar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/wctype.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/wordexp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xlocale.h
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/Mcrt1.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/Scrt1.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/crt1.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/crti.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/crtn.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/gcrt1.o
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libBrokenLocale.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libanl.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libc.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libc_nonshared.a
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libcidn.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libcrypt.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libdl.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libm.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnsl.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_compat.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_db.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_dns.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_files.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_hesiod.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_nis.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libnss_nisplus.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libpthread.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libpthread_nonshared.a
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libresolv.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/librt.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libthread_db.so
%{_prefix}/arm-frc-linux-gnueabi/usr/lib/libutil.so

%changelog
* Wed Jan 17 2018 David Chen <david.chen9909@gmail.com> 4.4-1 
- Initial version of the package

