Name:           arm-frc-linux-gnueabi-gcc
Version:        5.5.0
Release:        1%{?dist}
Summary:        The GNU Compiler Collection (arm-frc-linux-gnueabi) 


License:        GPLv3
URL:            http://gcc.gnu.org
Source0:        ftp://gcc.gnu.org/pub/gcc/releases/gcc-%{version}/gcc-%{version}.tar.gz
Source1:        config.patch

%description
Part of the FRC 2018 Power Up C++ tool-chain.

%global debug_package %{nil}

%prep
%setup -q -n gcc-%{version}

%define _target arm-frc-linux-gnueabi
%define procs 10

%build
echo %{version} > BASE-VER
patch -p1 < %{_sourcedir}/config.patch
mkdir gcc-build
cd gcc-build
../configure \
    --prefix=/usr \
    --program-prefix=%{_target}- \
    --infodir=%{_prefix}/%{_target}/share/info \
    --target=%{_target} \
    --enable-shared \
    --disable-nls \
    --enable-threads=posix \
    --enable-languages=c,c++ \
    --disable-multilib \
    --disable-multiarch \
    --with-sysroot=/usr/%{_target} \
    --with-build-sysroot=/usr/%{_target} \
    --with-as=%{_bindir}/%{_target}-as \
    --with-ld=%{_bindir}/%{_target}-ld \
    --with-cpu=cortex-a9 \
    --with-float=softfp \
    --with-fpu=vfp \
    --with-specs='%{save-temps: -fverbose-asm} %{funwind-tables|fno-unwind-tables|mabi=*|ffreestanding|nostdlib:;:-funwind-tables}' \
    --enable-lto \
    --with-pkgversion='GCC for FRC' \
    --with-cloog \
    --enable-poison-system-directories \
    --enable-plugin \
    --with-system-zlib \
    --disable-libmudflap \
    --disable-libgomp

make -j%{procs} all-gcc all-target-libsanitizer all-target-libgcc all-target-libstdc++-v3

%install
cd gcc-build
make "DESTDIR=%{buildroot}" install-gcc install-target-libsanitizer install-target-libgcc install-target-libstdc++-v3

cp -r %{buildroot}%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi %{buildroot}/usr/lib/gcc

strip %{buildroot}%{_bindir}/arm-frc-linux-gnueabi* 2>/dev/null || true
find %{buildroot}%{_prefix}/lib -type f -exec %{_bindir}/${_target}-strip --strip-unneeded {} \; 2>/dev/null || true

%files
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/algorithm
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/atomic_word.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/basic_file.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/c++allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/c++config.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/c++io.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/c++locale.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/cpu_defines.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/ctype_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/ctype_inline.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/cxxabi_tweaks.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/error_constants.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/extc++.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/gthr-default.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/gthr-posix.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/gthr-single.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/gthr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/messages_members.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/opt_random.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/os_defines.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/stdc++.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/stdtr1c++.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/bits/time_members.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/arm-frc-linux-gnueabi/ext/opt_random.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/array
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/atomic
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/auto_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/backward_warning.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/binders.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/hash_fun.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/hash_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/hash_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/hashtable.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/backward/strstream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/algorithmfwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/alloc_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/allocated_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/atomic_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/atomic_futex.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/atomic_lockfree_defines.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/basic_ios.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/basic_ios.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/basic_string.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/basic_string.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/boost_concept_check.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/c++0x_warning.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/c++14_warning.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/char_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/codecvt.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/concept_check.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/cpp_type_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/cxxabi_forced.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/deque.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/enable_special_members.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/exception_defines.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/exception_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/forward_list.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/forward_list.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/fstream.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/functexcept.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/functional_hash.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/gslice.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/gslice_array.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/hash_bytes.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/hashtable.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/hashtable_policy.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/indirect_array.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/ios_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/istream.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/list.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_classes.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_classes.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_conv.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_facets.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_facets.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_facets_nonio.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/locale_facets_nonio.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/localefwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/mask_array.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/memoryfwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/move.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/nested_exception.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/ostream.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/ostream_insert.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/parse_numbers.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/postypes.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/predefined_ops.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/ptr_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/quoted_string.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/random.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/random.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/range_access.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_automaton.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_automaton.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_compiler.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_compiler.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_constants.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_error.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_executor.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_executor.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_scanner.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/regex_scanner.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/shared_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/shared_ptr_atomic.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/shared_ptr_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/slice_array.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/sstream.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_algo.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_algobase.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_bvector.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_construct.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_deque.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_function.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_heap.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_iterator_base_funcs.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_iterator_base_types.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_list.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_multimap.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_multiset.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_numeric.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_pair.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_queue.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_raw_storage_iter.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_relops.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_set.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_stack.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_tempbuf.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_tree.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_uninitialized.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stl_vector.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stream_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/streambuf.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/streambuf_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/stringfwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/uniform_int_dist.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/unique_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/unordered_map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/unordered_set.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/uses_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/valarray_after.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/valarray_array.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/valarray_array.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/valarray_before.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bits/vector.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/bitset
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cassert
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ccomplex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cctype
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cerrno
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cfenv
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cfloat
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/chrono
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cinttypes
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ciso646
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/climits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/clocale
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cmath
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/codecvt
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/complex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/complex.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/condition_variable
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/csetjmp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/csignal
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdalign
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdarg
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdbool
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstddef
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdint
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdio
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstdlib
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cstring
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ctgmath
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ctime
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cwchar
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cwctype
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/cxxabi.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/array
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/bitset
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/debug.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/deque
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/formatter.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/forward_list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/functions.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/macros.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/multimap.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/multiset.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_container.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_iterator.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_local_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_local_iterator.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_sequence.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_sequence.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_unordered_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_unordered_container.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/safe_unordered_container.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/set.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/string
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/unordered_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/unordered_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/debug/vector
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/decimal/decimal
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/decimal/decimal.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/deque
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/exception
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/algorithm
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/any
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/chrono
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/filesystem
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/fs_dir.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/fs_fwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/fs_ops.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/fs_path.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/functional
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/lfts_config.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/optional
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/ratio
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/string_view
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/string_view.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/system_error
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/tuple
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/experimental/type_traits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/algorithm
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/aligned_buffer.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/alloc_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/array_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/atomicity.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/bitmap_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/cast.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/cmath
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/codecvt_specializations.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/concurrence.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/debug_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/enc_filebuf.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/extptr_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/functional
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/hash_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/hash_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/iterator
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/malloc_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/memory
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/mt_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/new_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/numeric
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/numeric_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/assoc_container.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/bin_search_tree_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/node_iterators.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/r_erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/rotate_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/bin_search_tree_/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/binary_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/entry_cmp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/entry_pred.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/point_const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/resize_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binary_heap_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_/binomial_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/binomial_heap_base_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/binomial_heap_base_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/branch_policy/branch_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/branch_policy/null_node_metadata.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/branch_policy/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/cc_ht_map_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/cmp_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/cond_key_dtor_entry_dealtor.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/debug_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/debug_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/entry_list_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/erase_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/erase_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/find_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/insert_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/insert_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/resize_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/resize_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/resize_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/size_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cc_hash_table_map_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/cond_dealtor.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/container_base_dispatch.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/debug_map_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/eq_fn/eq_by_less.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/eq_fn/hash_eq_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/debug_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/debug_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/erase_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/erase_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/find_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/find_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/gp_ht_map_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/insert_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/insert_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/iterator_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/resize_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/resize_no_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/resize_store_hash_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/gp_hash_table_map_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/direct_mask_range_hashing_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/direct_mod_range_hashing_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/linear_probe_fn_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/mask_based_range_hashing.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/mod_based_range_hashing.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/probe_fn_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/quadratic_probe_fn_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/ranged_hash_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/ranged_probe_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/sample_probe_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/sample_range_hashing.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/sample_ranged_hash_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/hash_fn/sample_ranged_probe_fn.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/left_child_next_sibling_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/node.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/point_const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/left_child_next_sibling_heap_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/constructor_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/entry_metadata_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/lu_map_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_map_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_policy/lu_counter_metadata.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/list_update_policy/sample_update_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/node_iterators.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/ov_tree_map_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/ov_tree_map_/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/pairing_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pairing_heap_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/insert_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/iterators_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/pat_trie_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/pat_trie_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/policy_access_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/r_erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/rotate_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/split_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/synth_access_traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/pat_trie_/update_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/priority_queue_base_dispatch.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/node.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/rb_tree_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rb_tree_map_/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/rc.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/rc_binomial_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/rc_binomial_heap_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/cc_hash_max_collision_check_resize_trigger_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/hash_exponential_size_policy_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_size_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/hash_prime_size_policy_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/hash_standard_resize_policy_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/sample_resize_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/sample_resize_trigger.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/resize_policy/sample_size_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/info_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/node.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/splay_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/splay_tree_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/splay_tree_/traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/standard_policies.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/constructors_destructor_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/debug_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/erase_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/find_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/insert_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/split_join_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/thin_heap_.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/thin_heap_/trace_fn_imps.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/tree_policy/node_metadata_selector.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/tree_policy/order_statistics_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/tree_policy/sample_tree_node_update.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/tree_trace_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/node_metadata_selector.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/order_statistics_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/prefix_search_node_update_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/sample_trie_access_traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/sample_trie_node_update.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/trie_policy_base.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/trie_policy/trie_string_access_traits_imp.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/type_utils.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/types_traits.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/unordered_iterator/const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/unordered_iterator/iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/unordered_iterator/point_const_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/detail/unordered_iterator/point_iterator.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/exception.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/hash_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/list_update_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/priority_queue.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/tag_and_trait.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/tree_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pb_ds/trie_policy.hpp
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pod_char_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pointer.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/pool_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/random
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/random.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/rb_tree
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/rc_string_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/rope
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/ropeimpl.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/slist
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/sso_string_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/stdio_filebuf.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/stdio_sync_filebuf.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/string_conversions.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/throw_allocator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/type_traits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/typelist.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/vstring.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/vstring.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/vstring_fwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ext/vstring_util.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/fenv.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/forward_list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/fstream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/functional
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/future
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/initializer_list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/iomanip
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ios
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/iosfwd
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/iostream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/istream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/iterator
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/limits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/locale
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/memory
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/mutex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/new
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/numeric
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ostream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/algo.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/algobase.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/algorithm
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/algorithmfwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/balanced_quicksort.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/basic_iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/checkers.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/compatibility.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/compiletime_settings.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/equally_split.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/features.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/find.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/find_selectors.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/for_each.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/for_each_selectors.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/iterator.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/list_partition.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/losertree.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/merge.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/multiseq_selection.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/multiway_merge.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/multiway_mergesort.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/numeric
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/numericfwd.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/omp_loop.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/omp_loop_static.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/par_loop.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/parallel.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/partial_sum.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/partition.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/queue.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/quicksort.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/random_number.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/random_shuffle.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/search.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/set_operations.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/settings.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/sort.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/tags.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/types.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/unique_copy.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/parallel/workstealing.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/array
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/bitset
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/deque
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/forward_list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_algos.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_container_size.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_hash_func.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_hashtable_size.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_list_to_slist.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_list_to_vector.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_map_to_unordered_map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_node.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_state.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_trace.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_vector_size.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/impl/profiler_vector_to_list.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/iterator_tracker.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/list
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/multimap.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/multiset.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/ordered_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/set.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/unordered_base.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/unordered_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/unordered_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/profile/vector
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/queue
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/random
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/ratio
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/regex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/scoped_allocator
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/shared_mutex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/sstream
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/stack
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/stdexcept
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/streambuf
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/string
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/system_error
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tgmath.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/thread
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/array
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/bessel_function.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/beta_function.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/ccomplex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cctype
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cfenv
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cfloat
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cinttypes
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/climits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cmath
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/complex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/complex.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cstdarg
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cstdbool
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cstdint
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cstdio
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cstdlib
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/ctgmath
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/ctime
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/ctype.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cwchar
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/cwctype
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/ell_integral.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/exp_integral.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/fenv.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/float.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/functional
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/functional_hash.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/gamma.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/hashtable.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/hashtable_policy.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/hypergeometric.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/inttypes.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/legendre_function.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/limits.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/math.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/memory
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/modified_bessel_func.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/poly_hermite.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/poly_laguerre.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/random
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/random.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/random.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/regex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/riemann_zeta.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/shared_ptr.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/special_function_util.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/stdarg.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/stdbool.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/stdint.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/stdio.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/stdlib.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/tgmath.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/tuple
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/type_traits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/unordered_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/unordered_map.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/unordered_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/unordered_set.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/utility
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/wchar.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr1/wctype.h
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/bool_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/bool_set.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/dynamic_bitset
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/dynamic_bitset.tcc
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/ratio
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tr2/type_traits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/tuple
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/type_traits
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/typeindex
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/typeinfo
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/unordered_map
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/unordered_set
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/utility
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/valarray
%{_prefix}/arm-frc-linux-gnueabi/include/c++/5.5.0/vector
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan.a
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan.la
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan.so.2
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan.so.2.0.0
%{_prefix}/arm-frc-linux-gnueabi/lib/libasan_preinit.o
%{_prefix}/arm-frc-linux-gnueabi/lib/libgcc_s.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libgcc_s.so.1
%{_prefix}/arm-frc-linux-gnueabi/lib/libsanitizer.spec
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.a
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.la
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so.6
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so.6.0.21
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so.6.0.21-gdb.py
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so.6.0.21-gdb.pyc
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++.so.6.0.21-gdb.pyo
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++fs.a
%{_prefix}/arm-frc-linux-gnueabi/lib/libstdc++fs.la
%{_prefix}/arm-frc-linux-gnueabi/lib/libsupc++.a
%{_prefix}/arm-frc-linux-gnueabi/lib/libsupc++.la
%{_prefix}/arm-frc-linux-gnueabi/lib/libubsan.a
%{_prefix}/arm-frc-linux-gnueabi/lib/libubsan.la
%{_prefix}/arm-frc-linux-gnueabi/lib/libubsan.so
%{_prefix}/arm-frc-linux-gnueabi/lib/libubsan.so.0
%{_prefix}/arm-frc-linux-gnueabi/lib/libubsan.so.0.0.0
%{_bindir}/arm-frc-linux-gnueabi-c++
%{_bindir}/arm-frc-linux-gnueabi-cpp
%{_bindir}/arm-frc-linux-gnueabi-g++
%{_bindir}/arm-frc-linux-gnueabi-gcc
%{_bindir}/arm-frc-linux-gnueabi-gcc-5.5.0
%{_bindir}/arm-frc-linux-gnueabi-gcc-ar
%{_bindir}/arm-frc-linux-gnueabi-gcc-nm
%{_bindir}/arm-frc-linux-gnueabi-gcc-ranlib
%{_bindir}/arm-frc-linux-gnueabi-gcov
%{_bindir}/arm-frc-linux-gnueabi-gcov-dump
%{_bindir}/arm-frc-linux-gnueabi-gcov-tool
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/cc1
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/cc1plus
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/collect2
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/crtbegin.o
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/crtbeginS.o
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/crtbeginT.o
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/crtend.o
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/crtendS.o
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include-fixed/README
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include-fixed/limits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include-fixed/syslimits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/arm_acle.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/arm_neon.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/float.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/iso646.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/mmintrin.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/sanitizer/asan_interface.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/sanitizer/common_interface_defs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/sanitizer/lsan_interface.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdalign.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdarg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdatomic.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdbool.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stddef.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdfix.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdint-gcc.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdint.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/stdnoreturn.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/unwind-arm-common.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/unwind.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/include/varargs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/fixinc.sh
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/fixinc_list
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/fixincl
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/gsyslimits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/include/README
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/include/limits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/macro_list
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/mkheaders
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/mkheaders.conf
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/mkinstalldirs
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/libgcc.a
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/libgcc_eh.a
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/libgcov.a
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.la
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so.0
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so.0.0.0
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/lto-wrapper
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/lto1
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/gengtype
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/gtype.state
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ada/gcc-interface/ada-tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/addresses.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/alias.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/all-tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/alloc-pool.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ansidecl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/asan.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/attribs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/auto-host.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/auto-profile.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/b-header-vars
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/basic-block.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/bb-reorder.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/bitmap.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/builtin-attrs.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/builtin-types.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/builtins.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/bversion.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-family/c-common.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-family/c-common.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-family/c-objc.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-family/c-pragma.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-family/c-pretty-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/c-tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/calls.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ccmp.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfg-flags.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfganal.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgbuild.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgcleanup.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgexpand.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfghooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgloop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgloopmanip.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cfgrtl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cgraph.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/chkp-builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cif-code.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cilk-builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cilk.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cilkplus.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/collect-utils.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/collect2-aix.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/collect2.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/conditions.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/aarch-common-protos.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/aout.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/arm-cores.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/arm-opts.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/arm-protos.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/arm.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/bpabi.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/elf.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/linux-eabi.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/linux-elf.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/arm/linux-gas.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/dbxelf.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/elfos.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/glibc-stdint.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/gnu-user.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/initfini-array.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/linux-android.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/linux-protos.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/linux.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/config/vxworks-dummy.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/configargs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/context.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/convert.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/coretypes.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/coverage.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cp/cp-tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cp/cp-tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cp/cxx-pretty-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cp/name-lookup.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cp/type-utils.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cppbuiltin.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cppdefault.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cpplib.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/cselib.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/data-streamer.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dbgcnt.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dbgcnt.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dbxout.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dce.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ddg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/debug.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/defaults.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/df.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dfp.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/diagnostic-color.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/diagnostic-core.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/diagnostic.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/diagnostic.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dojump.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dominance.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/domwalk.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/double-int.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dumpfile.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dwarf2asm.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/dwarf2out.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/emit-rtl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/errors.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/et-forest.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/except.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/explow.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/expmed.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/expr.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/fibonacci_heap.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/file-find.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/filenames.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/fixed-value.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/flag-types.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/flags.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/fold-const.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/function.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcc-plugin.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcc-symtab.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcc.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcov-counter.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcov-io.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcse-common.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gcse.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/generic-match.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gengtype.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/genrtl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gensupport.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ggc-internal.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ggc.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-builder.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-expr.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-fold.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-iterator.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-low.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-match.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-pretty-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-ssa.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-streamer.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple-walk.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimple.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimplify-me.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gimplify.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/glimits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graph.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graphds.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graphite-isl-ast-to-gimple.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graphite-poly.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graphite-scop-detection.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/graphite-sese-to-poly.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gsstruct.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gstab.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gsyms.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gsyslimits.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gtm-builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/gtype-desc.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hard-reg-set.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hash-map.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hash-set.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hash-table.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hashtab.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/highlev-plugin-common.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hosthooks-def.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hosthooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hw-doloop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/hwint.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ifcvt.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/inchash.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/incpath.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/input.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-addr.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-codes.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-constants.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-flags.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-modes.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/insn-notes.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/internal-fn.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/internal-fn.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/intl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-chkp.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-icf-gimple.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-icf.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-inline.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-prop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-ref.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-reference.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ipa-utils.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ira-int.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ira.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/is-a.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/java/java-tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/langhooks-def.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/langhooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lcm.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/libfuncs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/libiberty.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/limitx.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/limity.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/line-map.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/loop-unroll.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lower-subreg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lra-int.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lra.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lto-compress.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lto-section-names.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/lto-streamer.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/machmode.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/machmode.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/md5.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/mode-classes.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/objc/objc-tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/obstack.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/omega.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/omp-builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/omp-low.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/optabs.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/optabs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/options.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/opts-diagnostic.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/opts.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/output.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/params.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/params.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/pass-instances.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/pass_manager.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/passes.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/plugin-api.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/plugin-version.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/plugin.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/plugin.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/predict.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/predict.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/prefix.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/pretty-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/print-rtl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/print-tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/profile.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/read-md.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/real.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/realmpfr.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/recog.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/reg-notes.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/regcprop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/regrename.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/regs.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/regset.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/reload.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/resource.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtl-chkp.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtl-error.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtl-iter.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtl.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtl.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtlhash.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/rtlhooks-def.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/safe-ctype.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sanitizer.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sbitmap.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sched-int.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sdbout.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sel-sched-dump.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sel-sched-ir.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sel-sched.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sese.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/shrink-wrap.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/signop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sparseset.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/splay-tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sreal.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ssa-iterators.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/stab.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/statistics.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/stmt.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/stor-layout.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/streamer-hooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/stringpool.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/symbol-summary.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/symtab.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/sync-builtins.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/system.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/target-def.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/target-globals.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/target-hooks-macros.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/target.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/target.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/targhooks.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/timevar.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/timevar.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tm-preds.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tm.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tm_p.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/toplev.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/trans-mem.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-affine.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-browser.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-cfg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-cfgcleanup.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-check.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-chkp.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-chrec.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-core.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-data-ref.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-dfa.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-diagnostic.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-dump.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-eh.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-hasher.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-inline.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-into-ssa.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-iterator.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-nested.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-object-size.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-outof-ssa.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-parloops.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-pass.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-phinodes.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-pretty-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-scalar-evolution.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-address.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-alias.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-coalesce.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-dom.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-live.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-loop-ivopts.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-loop-manip.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-loop-niter.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-loop.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-operands.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-propagate.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-sccvn.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-ter.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-threadedge.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa-threadupdate.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssa.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-ssanames.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-stdarg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-streamer.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree-vectorizer.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/treestruct.def
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tsan.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/tsystem.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/typeclass.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/typed-splay-tree.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/ubsan.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/valtrack.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/value-prof.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/varasm.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/vec.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/version.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/vmsdbg.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/vtable-verify.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/wide-int-print.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/wide-int.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/xcoff.h
%{_prefix}/lib/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/include/xcoffout.h
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/cc1
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/cc1plus
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/collect2
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/fixinc.sh
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/fixincl
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/mkheaders
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/install-tools/mkinstalldirs
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.la
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so.0
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/liblto_plugin.so.0.0.0
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/lto-wrapper
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/lto1
%{_prefix}/libexec/gcc/arm-frc-linux-gnueabi/5.5.0/plugin/gengtype
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/__init__.py
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/__init__.pyc
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/__init__.pyo
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/__init__.py
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/__init__.pyc
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/__init__.pyo
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/printers.py
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/printers.pyc
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/printers.pyo
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/xmethods.py
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/xmethods.pyc
%{_datarootdir}/gcc-5.5.0/python/libstdcxx/v6/xmethods.pyo
%{_mandir}/man1/arm-frc-linux-gnueabi-cpp.1.gz
%{_mandir}/man1/arm-frc-linux-gnueabi-g++.1.gz
%{_mandir}/man1/arm-frc-linux-gnueabi-gcc.1.gz
%{_mandir}/man1/arm-frc-linux-gnueabi-gcov-dump.1.gz
%{_mandir}/man1/arm-frc-linux-gnueabi-gcov-tool.1.gz
%{_mandir}/man1/arm-frc-linux-gnueabi-gcov.1.gz
%{_mandir}/man7/fsf-funding.7.gz
%{_mandir}/man7/gfdl.7.gz
%{_mandir}/man7/gpl.7.gz
%{_prefix}/arm-frc-linux-gnueabi/share/info/cpp.info
%{_prefix}/arm-frc-linux-gnueabi/share/info/cppinternals.info
%{_prefix}/arm-frc-linux-gnueabi/share/info/dir
%{_prefix}/arm-frc-linux-gnueabi/share/info/gcc.info
%{_prefix}/arm-frc-linux-gnueabi/share/info/gccinstall.info
%{_prefix}/arm-frc-linux-gnueabi/share/info/gccint.info


%changelog
* Fri Jan 12 2018 David Chen <david.chen9909@gmail.com> 5.5.0-1 
- Initial version of the package
