Name:           arm-frc-linux-gnueabi-linux-api-headers
Version:        4.4
Release:        1%{?dist}
Summary:        Kernel headers for use in FRC 2018 Power Up

%define _basever 4.4-r0.22
%define _target arm-frc-linux-gnueabi

License:        GPLv2
URL:            http://www.gnu.org/software/libc
Source0:        http://download.ni.com/ni-linux-rt/feeds/2017/arm/ipk/cortexa9-vfpv3/linux-libc-headers-dev_%{_basever}_cortexa9-vfpv3.ipk

#BuildRequires:
#Requires:

%description
Kernel headers for use in FRC 2018 Power Up. Sanitized for use in userspace %{_target} 

%define version 4.4
%prep
rm -rf linux-api-headers-%{version}
mkdir -p linux-api-headers-%{version}
cd linux-api-headers-%{version}
ar x %{_sourcedir}/linux-libc-headers-dev_%{_basever}_cortexa9-vfpv3.ipk
tar -xzf data.tar.gz

%install
cd linux-api-headers-%{version}
mkdir -p %{buildroot}/%{_prefix}/%{_target}/usr/
cp -r ./usr/* %{buildroot}/%{_prefix}/%{_target}/usr/

%files
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/auxvec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/bitsperlong.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/errno-base.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/int-l64.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/int-ll64.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/ioctls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/ipcbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/kvm_para.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/mman-common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/mman.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/msgbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/param.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/posix_types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/resource.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/sembuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/setup.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/shmbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/shmparam.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/siginfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/signal-defs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/signal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/sockios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/stat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/statfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/swab.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/termbits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/ucontext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm-generic/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/auxvec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/bitsperlong.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/byteorder.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/hwcap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/ioctls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/ipcbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/kvm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/kvm_para.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/mman.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/msgbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/param.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/perf_regs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/posix_types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/ptrace.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/resource.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/sembuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/setup.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/shmbuf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/sigcontext.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/siginfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/signal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/sockios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/stat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/statfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/swab.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/termbits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/asm/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/drm_fourcc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/drm_mode.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/drm_sarea.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/exynos_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/i810_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/i915_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/mga_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/msm_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/nouveau_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/qxl_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/r128_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/radeon_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/savage_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/sis_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/tegra_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/via_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/virtgpu_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/drm/vmwgfx_drm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/acct.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/adb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/adfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/affs_hardblocks.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/agpgart.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/aio_abi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/am437x-vpfe.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/android/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/android/binder.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/apm_bios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/arcfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atalk.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_eni.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_he.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_idt77105.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_nicstar.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_tcp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atm_zatm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmapi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmarp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmbr2684.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmclip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmioc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmlec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmmpc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmppp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmsap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/atmsvc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/audit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/auto_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/auto_fs4.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/auxvec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ax25.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/b1lli.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/baycom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bcm933xx_hcs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/binfmts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/blkpg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/blktrace_api.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bpf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bpf_common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bpqether.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/bsg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/btrfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/byteorder/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/byteorder/big_endian.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/byteorder/little_endian.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/caif/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/caif/caif_socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/caif/if_caif.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/bcm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/error.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/gw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/can/raw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/capability.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/capi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cciss_defs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cciss_ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cdrom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cgroupstats.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/chio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cm4000_cs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cn_proc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/coda.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/coda_psdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/coff.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/connector.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/const.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cramfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cuda.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cyclades.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/cycx_cfm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dcbnl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dccp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dlm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dlm_device.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dlm_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dlm_plock.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dlmconstants.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dm-ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dm-log-userspace.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dqblk_xfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/audio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/ca.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/dmx.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/frontend.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/net.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/osd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/version.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/dvb/video.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/edd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/efs_fs_sb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/elf-em.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/elf-fdpic.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/elf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/elfcore.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/errno.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/errqueue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ethtool.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/eventpoll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fadvise.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/falloc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fanotify.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fcntl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fdreg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fib_rules.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fiemap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/filter.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/firewire-cdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/firewire-constants.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/flat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fou.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fsl_hypervisor.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/fuse.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/futex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/gameport.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/gen_stats.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/genetlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/gfs2_ondisk.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/gigaset_dev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/gsmmux.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hdlc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hdlc/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hdlc/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hdlcdrv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hdreg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hid.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hiddev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hidraw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hpet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hsi/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hsi/cs-protocol.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hsi/hsi_char.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hsr_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hw_breakpoint.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hyperv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/hysdn_if.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/i2c-dev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/i2c.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/i2o-dev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/i8k.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/icmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/icmpv6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_addr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_addrlabel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_alg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_arcnet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_arp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_bonding.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_bridge.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_cablemodem.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_eql.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_ether.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_fc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_fddi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_frad.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_hippi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_infiniband.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_link.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_ltalk.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_packet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_phonet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_plip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_ppp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_pppol2tp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_pppox.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_slip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_team.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_tun.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_tunnel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_vlan.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/if_x25.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/igmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/iio/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/iio/events.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/iio/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ila.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/in.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/in6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/in_route.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/inet_diag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/inotify.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/input-event-codes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/input.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ip6_tunnel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ip_vs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipmi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipmi_msgdefs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipsec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipv6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipv6_route.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ipx.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/irda.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/irqnr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdn/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdn/capicmd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdn_divertif.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdn_ppp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/isdnif.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/iso_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ivtv.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ivtvfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ixjuser.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/jffs2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/joystick.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kcmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kdev_t.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kernel-page-flags.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kernel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kernelcapi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kexec.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/keyboard.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/keyctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kvm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/kvm_para.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/l2tp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/libc-compat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/limits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/llc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/loop.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/lp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/lwtunnel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/magic.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/major.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/map_to_7segment.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/matroxfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mdio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/media-bus-format.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/media.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mei.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/membarrier.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/memfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mempolicy.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/meye.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mic_common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mic_ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mii.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/minix_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mman.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mmc/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mmc/ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mmtimer.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mpls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mpls_iptunnel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mqueue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mroute.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mroute6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/msdos_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/msg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/mtio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/n_r3964.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nbd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ncp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ncp_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ncp_mount.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ncp_no.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ndctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/neighbour.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/net.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/net_dropmon.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/net_namespace.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/net_tstamp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netconf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netdevice.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/ipset/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/ipset/ip_set.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/ipset/ip_set_bitmap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/ipset/ip_set_hash.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/ipset/ip_set_list.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_conntrack_common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_conntrack_ftp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_conntrack_sctp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_conntrack_tcp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_conntrack_tuple_common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_nat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_tables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nf_tables_compat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_acct.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_compat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_conntrack.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_cthelper.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_cttimeout.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_log.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/nfnetlink_queue.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/x_tables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_AUDIT.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_CHECKSUM.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_CLASSIFY.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_CONNMARK.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_CONNSECMARK.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_CT.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_DSCP.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_HMARK.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_IDLETIMER.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_LED.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_LOG.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_MARK.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_NFLOG.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_NFQUEUE.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_RATEEST.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_SECMARK.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_TCPMSS.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_TCPOPTSTRIP.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_TEE.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_TPROXY.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_addrtype.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_bpf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_cgroup.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_cluster.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_comment.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_connbytes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_connlabel.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_connlimit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_connmark.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_conntrack.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_cpu.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_dccp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_devgroup.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_dscp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_ecn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_esp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_hashlimit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_helper.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_ipcomp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_iprange.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_ipvs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_l2tp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_length.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_limit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_mac.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_mark.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_multiport.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_nfacct.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_osf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_owner.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_physdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_pkttype.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_policy.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_quota.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_rateest.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_realm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_recent.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_rpfilter.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_sctp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_set.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_state.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_statistic.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_string.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_tcpmss.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_tcpudp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_time.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter/xt_u32.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_arp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_arp/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_arp/arp_tables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_arp/arpt_mangle.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_802_3.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_among.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_arp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_arpreply.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_ip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_ip6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_limit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_log.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_mark_m.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_mark_t.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_nat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_nflog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_pkttype.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_redirect.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_stp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebt_vlan.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_bridge/ebtables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_decnet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ip_tables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_CLUSTERIP.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_ECN.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_LOG.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_REJECT.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_TTL.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_ah.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_ecn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv4/ipt_ttl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6_tables.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_HL.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_LOG.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_NPT.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_REJECT.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_ah.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_frag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_hl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_ipv6header.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_mh.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_opts.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netfilter_ipv6/ip6t_rt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netlink_diag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/netrom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs3.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs4.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs4_mount.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs_idmap.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfs_mount.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsacl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/cld.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/debug.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/export.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/nfsfh.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nfsd/stats.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nl80211.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nubus.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nvme.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/nvram.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/omap3isp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/omapfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/oom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/openvswitch.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/packet_diag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/param.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/parport.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/patchkey.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pci.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pci_regs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/perf_event.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/personality.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pfkeyv2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/phantom.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/phonet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pkt_cls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pkt_sched.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pktcdvd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pmu.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/poll.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/posix_types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ppdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ppp-comp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ppp-ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ppp_defs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/pps.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/prctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/psci.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ptp_clock.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ptrace.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/qnx4_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/qnxtypes.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/quota.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/radeonfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/raid/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/raid/md_p.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/raid/md_u.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/random.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/raw.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/rds.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/reboot.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/reiserfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/reiserfs_xattr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/resource.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/rfkill.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/romfs_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/rose.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/route.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/rtc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/rtnetlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/scc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sched.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/scif_ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/screen_info.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sctp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sdla.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/seccomp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/securebits.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/selinux_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sem.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/serial.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/serial_core.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/serial_reg.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/serio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/shm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/signal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/signalfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/smiapp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/snmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sock_diag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/socket.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sockios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sonet.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sonypi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sound.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/soundcard.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/spi/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/spi/spidev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/stat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/stddef.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/string.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sunrpc/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sunrpc/debug.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/suspend_ioctls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/swab.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/synclink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sysctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/sysinfo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/target_core_user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/taskstats.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_bpf.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_connmark.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_csum.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_defact.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_gact.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_ipt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_mirred.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_nat.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_pedit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_skbedit.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_act/tc_vlan.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_ematch/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_ematch/tc_em_cmp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_ematch/tc_em_meta.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_ematch/tc_em_nbyte.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tc_ematch/tc_em_text.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tcp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tcp_metrics.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/telephony.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/termios.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/thermal.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/time.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/times.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/timex.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tiocl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tipc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tipc_config.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tipc_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/toshiba.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tty.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/tty_flags.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/udf_fs_i.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/udp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/uhid.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/uinput.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/uio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/ultrasound.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/un.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/unistd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/unix_diag.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/audio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/cdc-wdm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/cdc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/ch11.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/ch9.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/functionfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/g_printer.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/gadgetfs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/midi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/tmc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usb/video.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usbdevice_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/usbip.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/userfaultfd.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/utime.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/utsname.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/uuid.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/uvcvideo.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/v4l2-common.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/v4l2-controls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/v4l2-dv-timings.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/v4l2-mediabus.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/v4l2-subdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/version.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/veth.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/vfio.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/vhost.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/videodev2.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_9p.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_balloon.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_blk.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_config.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_console.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_gpu.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_ids.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_input.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_net.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_pci.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_ring.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_rng.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_scsi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/virtio_types.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/vm_sockets.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/vt.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wait.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wanrouter.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/watchdog.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wimax.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wimax/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wimax/i2400m.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/wireless.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/x25.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/xattr.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/xfrm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/xilinx-v4l2-controls.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/zorro.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/linux/zorro_ids.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/misc/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/misc/cxl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/inftl-user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/mtd-abi.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/mtd-user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/nftl-user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/mtd/ubi-user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/hfi/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/hfi/hfi1_user.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/ib_user_cm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/ib_user_mad.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/ib_user_sa.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/ib_user_verbs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/rdma_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/rdma/rdma_user_cm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/cxlflash_ioctl.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/fc/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/fc/fc_els.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/fc/fc_fs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/fc/fc_gs.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/fc/fc_ns.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/scsi_bsg_fc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/scsi_netlink.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/scsi/scsi_netlink_fc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/asequencer.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/asound.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/asound_fm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/compress_offload.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/compress_params.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/emu10k1.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/firewire.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/hdsp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/hdspm.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/sb16_csp.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/sound/sfnt_info.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/uapi/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/video/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/video/edid.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/video/sisfb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/video/uvesafb.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xen/.install
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xen/evtchn.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xen/gntalloc.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xen/gntdev.h
%{_prefix}/arm-frc-linux-gnueabi/usr/include/xen/privcmd.h


%changelog
* Wed Jan 17 2018 David Chen <david.chen9909@gmail.com> 4.4-1 
- Initial version of the package

